# Generated by Django 3.2 on 2023-04-15 18:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[\\\\w.@+-]+\\\\z')], verbose_name='Имя пользователя'),
        ),
    ]
