# Generated by Django 3.2 on 2023-04-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20230415_0951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('pub_date',), 'verbose_name': 'Рецензия', 'verbose_name_plural': 'Рецензии'},
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(help_text='Текст рецензии', max_length=200, verbose_name='Ввод текста'),
        ),
    ]
